### ISSUE TITLE
Need better way to integrate GIT for ABAP

### ISSUE THREAD

**Issue by fareez-ahamed** [Gh14Cc10/google-api-ABAP-client#1]
Hi,

I would like to join but we need better way to integrate GIT with ABAP... why shouldn't we kick start something for that? Count me in always :smiley:

**Comment by Gh14Cc10** [comment]
HI fareez-ahamed, 
it's a great idea! For now we can use SAPLINK, i am adding you as collaborator

**Comment by fareez-ahamed** [comment]
But one min...

Do I need a google glass for working on it n test it?? :O I don't have actually.... Not enough knowledge about Google glass API as well (but I hope I can learn that no issues)

**Comment by Gh14Cc10** [comment]
not needed :)

you can use the playground

https://developers.google.com/glass/tools-downloads/playground

**Comment by fareez-ahamed** [comment]
Sure... Thanks :)

Let me check it...

**Comment by renatocode** [comment]
Hi!

Here is a better way for integrate and install a plugin "abapGit".

**Comment by ivanfemia** [comment]
@renatocode it would be better if you ask in the [abapGit](https://github.com/larshp/abapGit) repo
